import csv
from datetime import datetime
from cloudmesh.common.StopWatch import StopWatch
from cloudmesh.gpu.gpu import Gpu
import subprocess
import train_setup  # links training data to its labels
import os
import getpass

if __name__ == "__main__":
    # Step 1: Compute username and current timestamp
    username = getpass.getuser()
    now = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Step 2: Get GPU info
    gpu = Gpu()
    all_vram = [card['fb_memory_usage']['total'] for card in gpu._smi]
    all_gpu_names = [card["product_name"] for card in gpu.system()]

    cuda_visible = os.environ.get("CUDA_VISIBLE_DEVICES", None)
    if cuda_visible:
        print(f"CUDA_VISIBLE_DEVICES: {cuda_visible}")
        try:
            indices = [int(x.strip()) for x in cuda_visible.split(",") if x.strip() != ""]
        except ValueError:
            indices = []
        selected_vram = [all_vram[i] for i in indices if i < len(all_vram)]
        selected_gpu_names = [all_gpu_names[i] for i in indices if i < len(all_gpu_names)]
        vram = ", ".join(selected_vram)
        gpu_name = ", ".join(selected_gpu_names)
    else:
        vram = " ".join(all_vram)
        gpu_name = " ".join(all_gpu_names)

    # Create safe strings for filenames
    gpu_name_safe = gpu_name.replace(" ", "_").replace(",", "-")
    # We'll set cpu_name_safe later after we obtain sysinfo

    # Step 3: If running in Apptainer, create an output folder and change into it.
    # This ensures that files generated by the darknet subprocess go into this directory.
    if "APPTAINER_ENVIRONMENT" in os.environ:
        print("Running in Apptainer environment")
        output_dir = os.path.join("/outputs", f"benchmark_{username}_{gpu_name_safe}_{now}")
        os.makedirs(output_dir, exist_ok=True)
        os.chdir(output_dir)
        print(f"Changed directory to output folder: {output_dir}")
        darknetloc = '/host_workspace/darknet/build/src-cli/darknet'
    else:
        print("Running non-apptainer")
        darknetloc = 'darknet'

    # Step 5: Run benchmark (this will create files in the current working directory)
    StopWatch.start("benchmark")
    subprocess.call(
        f"{darknetloc} detector -map -dont_show -verbose -nocolor train /workspace/LegoGears_v2/LegoGears.data /workspace/LegoGears_v2/LegoGears.cfg 2>&1 | tee training_output.log",
        shell=True)
    StopWatch.stop("benchmark")
    benchmark_result = StopWatch.get_benchmark()

    # Step 6: Extract sysinfo and benchmark results
    sysinfo = benchmark_result["sysinfo"]
    benchmark = benchmark_result["benchmark"]["benchmark"]

    # Now that we have sysinfo, create a safe CPU name string.
    cpu_name_safe = sysinfo["cpu"].replace(" ", "_")

    data = {
        "Benchmark Time (s)": benchmark["time"],
        "CPU Name": sysinfo["cpu"],
        "CPU Threads": sysinfo["cpu_threads"],
        "GPU Name": gpu_name,
        "GPU VRAM": vram,
        "Total Memory": sysinfo["mem.total"],
        "OS": sysinfo["uname.system"],
        "Architecture": sysinfo["uname.machine"],
        "Python Version": sysinfo["python.version"],
    }

    # Step 7: Create a unique CSV filename in the current (output) directory
    filename = f"benchmark_{username}_{gpu_name_safe}_{cpu_name_safe}_{now}.csv"
    with open(filename, mode="w", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=data.keys())
        writer.writeheader()
        writer.writerow(data)

    print(f"Benchmark results saved to {filename}")
